# -*- coding: utf-8 -*-
"""Health_insurance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t2T8YPLtG_piQFAlZRPxYO9s-RQBiz5n

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('health_insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
age = X[:, 0]
print(age)
print(X)
print(y)

"""## Encode Categorical Data


"""

# encoding sex and smoker column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:,1])
X[:, 4] = le.fit_transform(X[:,4])

"""## Encoding the Region column"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

"""## Splitting the dataset into Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## Training the model"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)

"""## Making a single prediction

> Predict a health insurance charges for a person with age = 55, sex = female, bmi = 30, 0 children, smoker - no and region = southwest  







"""

print(regressor.predict([[0,0,0,1,55,1,30,0,0]]))

"""## Getting the final linear regression equatin wuth the values of the coefficients"""

print(regressor.coef_)
print(regressor.intercept_)